mysql: &mysql
  adapter: mysql2

postgresql: &postgres
  adapter: postgresql
  pool: <%= ENV['CONCURRENCY'].to_i %>
  min_messages: ERROR

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i %>
  timeout: 5000
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  database: <%= ENV['DB_NAME'] %>_test
  <<: *defaults

production:
  <<: *defaults
