mysql: &mysql
  adapter: mysql2

postgresql: &postgres
  adapter: postgresql
  pool: <%= ENV['CONCURRENCY'].to_i + 20 %>
  min_messages: ERROR

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i + 20 %>
  timeout: 5000
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || "127.0.0.1" %>
  port: <%= ENV['DB_PORT'] || 3306 %>

  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  database: <%= ENV['DB_NAME'] %>_test
  <<: *defaults

production:
  <<: *defaults

stage:
  <<: *defaults
