# octopus:
#   replicated: true
#   fully_replicated: true
#   enviroments:
#     - development
#     - production
#   defaults: &defaults
#     slave:
#       adapter: mysql2
#       encoding: utf8mb4
#       database: <%= ENV['DB_NAME'] %>
#       username: <%= ENV['DB_USERNAME'] %>
#       password: <%= ENV['DB_PASSWORD'] %>
#       host: <%= ENV['DB_SLAVE_HOST'] || ENV['DB_HOST'] || "127.0.0.1" %>
#       port: <%= ENV['DB_PORT'] || 3306 %>
#   development:
#     <<: *defaults
#   production:
#     <<: *defaults
